<?php

namespace Database\Seeders;

use App\Models\Escola;
use Illuminate\Database\Seeder;

class EscolaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $escolas = [
            [
                'id'    => 1,
                'escola' => 'Adolfina Leonor Soares Dos Santos',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 2,
                'escola' => 'Adriana Aparecida Cassiano',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 3,
                'escola' => 'Aida de Almeida Castro Grazioli',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 4,
                'escola' => 'Alaor Xavier Junqueira',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 5,
                'escola' => 'Antonia Antunes Arouca',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 6,
                'escola' => 'Antonia Ribeiro Da Silva',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 7,
                'escola' => 'Antonio De Freitas Avelar',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 8,
                'escola' => 'Aparecida Maria Pires De Meneses',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 9,
                'escola' => 'Benedito Inacio Soares',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 10,
                'escola' => 'Bernardo Ferreira Louzada',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 11,
                'escola' => 'Carlos Altero Ortega',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 12,
                'escola' => 'Carlos De Almeida Rodrigues Dr.',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 13,
                'escola' => 'CEI do Bairro Poiares',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 14,
                'escola' => 'Celia Rocha Lobo',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 15,
                'escola' => 'Creche Santo Antonio',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 16,
                'escola' => 'Edna Maria Nogueira Ferraz',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 17,
                'escola' => 'Elisa Butschkau',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 18,
                'escola' => 'Ester Nunes De Souza',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 19,
                'escola' => 'Euclydes Ferreira',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 20,
                'escola' => 'Francisco Assis De Carvalho',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 21,
                'escola' => 'Geraldo De Lima',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 22,
                'escola' => 'Honorina Pacheco Correa',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 23,
                'escola' => 'Jane Urbano Focesi',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 24,
                'escola' => 'Joao Baptista Gardelin',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 25,
                'escola' => 'Joao Benedito Marcondes',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 26,
                'escola' => 'Joao Lino Da Cruz',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 27,
                'escola' => 'Joao Thimoteo Do Rosario',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 28,
                'escola' => 'Jorge Passos',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 29,
                'escola' => 'Leonor Mendes De Barros',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 30,
                'escola' => 'Lucio Jacinto Dos Santos',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 31,
                'escola' => 'Luiz Ribeiro Muniz',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 32,
                'escola' => 'Luiz Silvar Do Prado',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 33,
                'escola' => 'Maria Aparecida De Carvalho',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 34,
                'escola' => 'Maria Aparecida Ujio',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 35,
                'escola' => 'Maria Carlita Saraiva Guedes',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 36,
                'escola' => 'Maria De Lourdes Lucarelli Perez',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 37,
                'escola' => 'Maria Elma Mansano',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 38,
                'escola' => 'Maria Eugenia Aranha Chodounsky',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 39,
                'escola' => 'Maria Moraes De Oliveira',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 40,
                'escola' => 'Maria Onicie Dias Pereira',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 41,
                'escola' => 'Maria Thereza De Souza Castro',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 42,
                'escola' => 'Masako Sone',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 43,
                'escola' => 'Meimei',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 44,
                'escola' => 'Messias Mendes De Souza',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 45,
                'escola' => 'Oswaldo Ferreira',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 46,
                'escola' => 'Pedro Joao De Oliveira',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 47,
                'escola' => 'Regina Celia Santos Chapira Blaustein',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 48,
                'escola' => 'Ricardo Luques Sammarco Serra',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 49,
                'escola' => 'Santina Nardi Marques',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 50,
                'escola' => 'Severino Vitoriano Dos Santos',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 51,
                'escola' => 'Telma Do Amarante Veiga Santos',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 52,
                'escola' => 'Thereza Yanesse Schmidt Cardozo',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 53,
                'escola' => 'Vera Da Silva Santos',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 54,
                'escola' => 'Yasutada Nasu',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 55,
                'escola' => 'Seduc',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 56,
                'escola' => 'CIASE - Governador Adhemar Pereira de Barros',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 57,
                'escola' => 'CIASE - Wilson Francisco Valente',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 58,
                'escola' => 'CRIE Casa Branca',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 59,
                'escola' => 'CRIE Pereque',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 60,
                'escola' => 'CRIE Tinga',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 61,
                'escola' => 'UNIVESP',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
            [
                'id'    => 62,
                'escola' => 'Precisa alterar',
                'cie'       => '402862',
                'regiao'    => 'Centro',
                'bairro'    => 'Sumare',
                'endereco'  => 'Av. Siqueira Campos',
                'telefone'  => '38812521',
            ],
        ];

        Escola::insert($escolas);
    }
}
